mood:
  alert: '&e'
  error: '&c'
  notice: '&9'

object:
  command: '[&b{1}](!"{2}" "&cClick to run command.")'
  command_suggestion: '[&b{1}](?"{2}" "&cClick to edit command.")'
  input: '''&6{?}{#.#}''' # Raw user input
  input_sanitized: '&6{?}{#.#}' # Input that has been corrected by a plugin
  item: '&6{?}{#.#}'
  player: '&6{?}{#.#}' # Matched player's name
  url: '[&b{1}](>"{2}" "Click for URL")'
  usage: '&4USAGE: &c{1}'