formats:
  moods:
    error: '&c'
    notice: '&9'

  objects:
    item: '&6' # Generic item
    input: '''&6{?}{mood=.}'''
    input_sanitized: '&6{?}{mood=.}'
    player_online: '&a' # A matched online player's name
    player_offline: '&c' # A matched offline player's name
    tag: '&8[&6{?}&8] '
    usage: '&4USAGE: &c{?}'