formats:
  moods:
    error: '&c'
    notice: '&9'

  objects:
    command: '[&b{1}];(cmd:{2});(txt:&cClick to run command.);'
    command_suggestion: '[&b{1}];(scmd:{2});(txt:&aClick to edit command.);'
    description_not_set: '{mood=error}&oNo description set.'
    item: '&6{?}{mood=.}' # Generic item
    input: '''&6{?}{mood=.}'''
    input_sanitized: '&6{?}{mood=.}'
    player: '&6{?}{mood=.}' # Matched player's name
    player_online: '&a{?}{mood=.}' # A matched online player's name
    player_offline: '&c{?}{mood=.}' # A matched offline player's name
    tag: '&8[&6{?}&8] '
    url: '[&b{1}];(url:{2});'
    usage: '&4USAGE: &c{?}'