name: ${project.name}
version: ${project.version}
description: '${project.description}'
depend: []
softdepend: []
authors: [${project.authors}]
website: ${project.url}
main: ${project.mainClass}
commands:
  flexmodules:
    description: 'View the modules of a loaded FlexPlugin'
    aliases: []
  flexreload:
    description: 'Ability to reload a FlexPlugin'
    aliases: []