name: ${project.name}
version: ${project.version}
description: '${project.description}'
depend: [Vault]
softdepend: []
authors: [${project.authors}]
website: ${project.url}
main: ${project.mainClass}
