name: ${project.name}
version: ${project.version}
description: '${project.description}'
depend: []
softdepend: [Towny, Vault]
authors: [${project.authors}]
website: ${project.url}
main: ${project.mainClass}
commands:
  flexadmin:
    description: 'Utility command primarily for debugging purposes'
    aliases: []
  flexmodules:
    description: 'View the modules of a loaded FlexPlugin'
    aliases: []
  flexreload:
    description: 'Reload command for FlexPlugin implementations'
    aliases: []
  flexsave:
    description: 'Save command for FlexPlugin implementations'
    aliases: []

permissions:
  ##########
  # Groups #
  ##########

  flexlib.admin:
    default: op
    children:
      flexlib.reload: true
      flexlib.save: true
      flexlib.modules: true
      flexlib.bypass.vanish: true

  flexlib.user:
    default: true
    children: {}

  #------------------------------------------------------------------------------------------------#

  #########
  # Nodes #
  #########

  flexlib.reload:
    default: false
    description: 'Ability to reload FlexPlugin implementations'
  flexlib.save:
    default: false
    description: 'Ability to save FlexPlugin implementations'

  flexlib.modules:
    default: false
    dsecription: 'Ability to view a FlexPlugin''s modules'

  flexlib.bypass.vanish:
    default: false
    description: 'Ability to bypass FlexLib vanish checks'