storage:
  type: 'YAML' # YAML, MYSQL
  MySQL:
    host: 'localhost'
    port: 3306
    database: 'minecraft'
    username: 'username'
    password: 'password'
    prefix: 'ft_'
    consumer:
      run time: 1000
      run interval: 40
  YAML:
    file: 'tickets.yml'