config:
  page items: 10 # The number of items per page
  line length: 52

headers:
  default: # If not defined, defaults to this
    left:
      prefix: '&8&m'
      text: '-'
      suffix: '&r'
    right:
      prefix: '&8&m'
      text: '-'
      suffix: ''
  page:
    center: '&a{KEY} &c(pg.{PAGE}/{MAXPAGES})'
  page_subtitle:
    center: '&a{KEY}: &6{VALUE} &c(pg.{PAGE}/{MAXPAGES})'
  title:
    center: '&a{KEY}'
  subtitle:
    center: '&a{KEY}: &6{VALUE}'
  help:
    center: '&aHelp: &6{KEY} &c(pg.{PAGE}/{MAXPAGES})'